# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1

EAPI=8

CRATES="
	addr2line@0.22.0
	adler@1.0.2
	ahash@0.8.11
	allocator-api2@0.2.18
	anstream@0.6.15
	anstyle@1.0.8
	anstyle-parse@0.2.5
	anstyle-query@1.1.1
	anstyle-wincon@3.0.4
	async-channel@2.3.1
	autocfg@1.3.0
	backtrace@0.3.73
	bitflags@2.6.0
	bluer@0.17.3
	bytes@1.6.1
	cassowary@0.3.0
	castaway@0.2.3
	cc@1.1.7
	cfg-if@1.0.0
	cfg_aliases@0.2.1
	clap@4.5.11
	clap_builder@4.5.11
	clap_derive@4.5.11
	clap_lex@0.7.2
	colorchoice@1.0.2
	compact_str@0.8.0
	concurrent-queue@2.5.0
	coolor@0.9.0
	crossbeam-utils@0.8.20
	crossterm@0.27.0
	crossterm@0.28.1
	crossterm_winapi@0.9.1
	custom_debug@0.6.1
	custom_debug_derive@0.6.1
	darling@0.20.10
	darling_core@0.20.10
	darling_macro@0.20.10
	dbus@0.9.7
	dbus-crossroads@0.5.2
	dbus-tokio@0.7.6
	dirs@5.0.1
	dirs-sys@0.4.1
	displaydoc@0.2.5
	either@1.13.0
	equivalent@1.0.1
	errno@0.3.9
	event-listener@5.3.1
	event-listener-strategy@0.5.2
	fnv@1.0.7
	futures@0.3.30
	futures-channel@0.3.30
	futures-core@0.3.30
	futures-executor@0.3.30
	futures-io@0.3.30
	futures-macro@0.3.30
	futures-sink@0.3.30
	futures-task@0.3.30
	futures-util@0.3.30
	getrandom@0.2.15
	gimli@0.29.0
	hashbrown@0.14.5
	heck@0.5.0
	hermit-abi@0.3.9
	hex@0.4.3
	ident_case@1.0.1
	indexmap@2.2.6
	instability@0.3.2
	is_terminal_polyfill@1.70.1
	itertools@0.12.1
	itertools@0.13.0
	itoa@1.0.11
	lazy_static@1.5.0
	libc@0.2.155
	libdbus-sys@0.2.5
	libredox@0.1.3
	linux-raw-sys@0.4.14
	lock_api@0.4.12
	log@0.4.22
	lru@0.12.3
	macaddr@1.0.1
	memchr@2.7.4
	miniz_oxide@0.7.4
	mio@0.8.11
	mio@1.0.1
	nix@0.29.0
	num-derive@0.4.2
	num-traits@0.2.19
	object@0.36.2
	once_cell@1.19.0
	option-ext@0.2.0
	parking@2.2.0
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	paste@1.0.15
	pin-project@1.1.5
	pin-project-internal@1.1.5
	pin-project-lite@0.2.14
	pin-utils@0.1.0
	pkg-config@0.3.30
	proc-macro2@1.0.86
	quote@1.0.36
	ratatui@0.28.0
	redox_syscall@0.5.3
	redox_users@0.4.5
	rustc-demangle@0.1.24
	rustix@0.38.34
	rustversion@1.0.17
	ryu@1.0.18
	scopeguard@1.2.0
	serde@1.0.204
	serde_derive@1.0.204
	serde_json@1.0.121
	serde_spanned@0.6.7
	signal-hook@0.3.17
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.2
	slab@0.4.9
	smallvec@1.13.2
	socket2@0.5.7
	static_assertions@1.1.0
	strsim@0.11.1
	strum@0.26.3
	strum_macros@0.26.4
	syn@2.0.72
	synstructure@0.13.1
	terminal-light@1.4.0
	thiserror@1.0.63
	thiserror-impl@1.0.63
	tokio@1.39.2
	tokio-macros@2.4.0
	tokio-stream@0.1.15
	toml@0.8.16
	toml_datetime@0.6.7
	toml_edit@0.22.17
	tui-input@0.10.0
	unicode-ident@1.0.12
	unicode-segmentation@1.11.0
	unicode-truncate@1.1.0
	unicode-width@0.1.13
	utf8parse@0.2.2
	uuid@1.10.0
	version_check@0.9.5
	wasi@0.11.0+wasi-snapshot-preview1
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	winnow@0.6.16
	xterm-query@0.4.1
	zerocopy@0.7.35
	zerocopy-derive@0.7.35
"

inherit cargo

DESCRIPTION="TUI for managing bluetooth on Linux"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/pythops/bluetui"
SRC_URI="
	https://github.com/pythops/bluetui/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"
